# Generated by Django 4.1 on 2023-04-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_availability_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='type_unit',
        ),
    ]
