# Generated by Django 4.2.1 on 2023-06-30 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=50, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('theme', models.CharField(choices=[('theme 1', 'theme 1'), ('theme 2', 'theme 2'), ('theme 3', 'theme 3')], default='theme 1', max_length=50)),
                ('about', models.TextField(blank=True, default=' ')),
                ('position', models.CharField(blank=True, default=' ', max_length=255)),
                ('activation_field', models.CharField(choices=[('درمانی', 'درمانی'), ('آموزشی', 'آموزشی'), ('اداری', 'اداری')], default='درمانی', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('یک به یک', 'یک به یک'), ('گروهی', 'گروهی')], max_length=50)),
                ('time_unit', models.DecimalField(decimal_places=1, default=1.5, max_digits=5)),
                ('place', models.CharField(choices=[('حضوری', 'حضوری'), ('گوگل میت', 'گوگل میت'), ('اسکایپ', 'اسکایپ'), ('واتساپ', 'واتساپ')], max_length=50)),
                ('address', models.CharField(blank=True, default=' ', max_length=255)),
                ('massage', models.TextField(blank=True)),
                ('event_domain', models.CharField(max_length=255)),
                ('is_enable', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default=datetime.date(2023, 6, 30), max_length=255)),
                ('start_hour', models.CharField(default='00:00', max_length=255)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('end_hour', models.CharField(default='00:00', max_length=255)),
                ('is_enable', models.BooleanField(default=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('approve', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event_time')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
