# Generated by Django 4.1 on 2023-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='type_unit',
            field=models.CharField(choices=[('minute', 'minute'), ('hour', 'hour')], default='hour', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('profile',)},
        ),
    ]
