# Generated by Django 4.2.1 on 2023-06-01 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_time_end_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_time',
            name='date',
            field=models.CharField(default=datetime.date(2023, 6, 1), max_length=255),
        ),
        migrations.AlterField(
            model_name='event_time',
            name='end_hour',
            field=models.CharField(default='00:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='event_time',
            name='start_hour',
            field=models.CharField(default='00:00', max_length=255),
        ),
    ]
