# Generated by Django 4.1 on 2023-06-23 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_time_date_alter_event_time_end_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('گوگل میت', 'گوگل میت'), ('اسکایپ', 'اسکایپ'), ('واتساپ', 'واتساپ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event_time',
            name='date',
            field=models.CharField(default=datetime.date(2023, 6, 23), max_length=255),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
