# Generated by Django 4.1 on 2023-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_availability_type_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('end_hour', models.DateTimeField(blank=True, null=True)),
                ('is_enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='time_unit',
        ),
        migrations.AddField(
            model_name='event',
            name='time_unit',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=5),
        ),
    ]
