# Generated by Django 4.1 on 2023-05-13 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_time_event_event_time_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_time',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.event_time'),
        ),
    ]
